[VEL-23895] Активатор. Методы работы с сертификатами
rentsoft/velvica-js-client pull request #29
Opened 2021-05-21 08:08 UTC by nartzis

2021-05-21 10:41 UTC, IgorVodka requested changes

2021-05-21 10:41 UTC, IgorVodka commented on src/CertApi.js
> +      })
```suggestion
        grantType: 'client_credentials'
      });
```

2021-05-21 10:41 UTC, IgorVodka commented on src/CertApi.js
> +        clientSecret: clientSecret,
```suggestion
        clientId,
        clientSecret,
```

2021-05-21 10:41 UTC, IgorVodka commented on src/CertApi.js
> +          body:  JSON.stringify(
форматирование, пробелы, backtick string незачем

2021-05-21 10:41 UTC, IgorVodka commented on src/CertApi.js
> +                cert,
форматирование, пробелы, backtick string незачем

2021-05-21 14:55 UTC, nartzis commented on src/CertApi.js
> +                cert,
Поправил

2021-05-21 14:56 UTC, nartzis commented on src/CertApi.js
> +          body:  JSON.stringify(
Поправил

2021-05-21 14:56 UTC, nartzis commented on src/CertApi.js
> +        clientSecret: clientSecret,
Поправил

2021-05-21 14:56 UTC, nartzis commented on src/CertApi.js
> +      })
Поправил

2021-05-21 16:20 UTC, IgorVodka approved these changes
не везде стиль такой, как хотелось бы (т.е. не везде соответствует стилю из остальных фрагментов кода), но мне кажется, что это нужно решать вводом линтера, а не бесконечным ревью

2021-05-24 14:50 UTC, koshker requested changes

2021-05-24 14:50 UTC, koshker commented on src/CertApi.js
> +  async certInfo(cert, email, verificationCode) {
```suggestion
  async fetchCertInfo(cert, email, verificationCode) {
```

2021-05-24 14:50 UTC, koshker commented on src/CertApi.js
> +  async certActivate(cert, email, verificationCode) {
```suggestion
  async activateCert(cert, email, verificationCode) {
```

2021-05-25 05:47 UTC, nartzis commented on src/CertApi.js
> +  async certInfo(cert, email, verificationCode) {
Поправил

2021-05-25 05:47 UTC, nartzis commented on src/CertApi.js
> +  async certActivate(cert, email, verificationCode) {
Поправил

2021-05-25 06:21 UTC, koshker approved these changes

2021-06-01 09:42 UTC, koshker commented
@nartzis Проставь тег с версией и можно мержить.

2021-06-03 15:50 UTC, IgorVodka approved these changes

2021-06-03 17:58 UTC, merged